/**
 * geo-deploy.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Generates and deploys robots.txt and llms.txt to a site's web root.
 *
 * Uses the site's deploy webhook (if configured) or FTP credentials.
 * - robots.txt: includes the site's Sitemap directive + permissive AI bot rules.
 * - llms.txt:   minimal Markdown manifest describing the site for LLM crawlers.
 *
 * Both files are idempotent — re-deploying replaces the previous version.
 * ─────────────────────────────────────────────────────────────────────────────
 */

import { uploadFileViaFtp } from '../utils/ftp.js';
import { logSystem } from '../utils/logger.js';
import { type Site } from '../db/database.js';

function normaliseDomain(domain: string): string {
  let host = domain;
  if (host.includes('://')) host = host.split('://')[1];
  if (host.includes('/')) host = host.split('/')[0];
  return host;
}

export function buildRobotsTxt(site: Site): string {
  const host = normaliseDomain(site.domain);
  const sitemapUrl = site.sitemap_url || `https://${host}/sitemap.xml`;
  return [
    '# Generated by SEO Website Indexer',
    '# This file allows search engine and AI crawlers full access by default.',
    '',
    'User-agent: *',
    'Allow: /',
    '',
    '# AI / LLM crawlers — explicitly allowed.',
    'User-agent: GPTBot',
    'Allow: /',
    '',
    'User-agent: Google-Extended',
    'Allow: /',
    '',
    'User-agent: ClaudeBot',
    'Allow: /',
    '',
    'User-agent: PerplexityBot',
    'Allow: /',
    '',
    'User-agent: CCBot',
    'Allow: /',
    '',
    `Sitemap: ${sitemapUrl}`,
    '',
  ].join('\n');
}

export function buildLlmsTxt(site: Site): string {
  const host = normaliseDomain(site.domain);
  return [
    `# ${site.name || host}`,
    '',
    `> ${site.name || host} — primary entry point for LLM and AI-assistant crawlers.`,
    '',
    '## Site',
    '',
    `- Homepage: https://${host}/`,
    `- Sitemap:  ${site.sitemap_url || `https://${host}/sitemap.xml`}`,
    '',
    '## Policy',
    '',
    '- AI crawlers are welcome to read public content.',
    '- Please respect `robots.txt` for any disallowed paths.',
    '- For attribution, link back to the source page.',
    '',
  ].join('\n');
}

/** Deterministic llms-sitemap.xml listing the site's LLM files (llmstxt.org). */
export function buildLlmsSitemap(site: Site, hasFull = false): string {
  const host = normaliseDomain(site.domain);
  const now = new Date().toISOString();
  const entry = (loc: string) => `  <url>\n    <loc>${loc}</loc>\n    <lastmod>${now}</lastmod>\n  </url>`;
  const urls = [entry(`https://${host}/llms.txt`)];
  if (hasFull) urls.push(entry(`https://${host}/llms-full.txt`));
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.join('\n')}\n</urlset>\n`;
}

export type DeployTarget = 'robots' | 'llms';

export interface DeployResult {
  target: DeployTarget;
  ok: boolean;
  method: 'webhook' | 'ftp' | 'none';
  message: string;
}

async function deployViaWebhook(site: Site, filename: string, content: string): Promise<DeployResult | null> {
  if (!site.deploy_webhook_url) return null;
  try {
    const res = await fetch(site.deploy_webhook_url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ filename, content, contentType: 'text/plain' }),
      signal: AbortSignal.timeout(10_000),
    });
    if (!res.ok) {
      return { target: filename === 'robots.txt' ? 'robots' : 'llms', ok: false, method: 'webhook', message: `Webhook returned HTTP ${res.status}` };
    }
    return { target: filename === 'robots.txt' ? 'robots' : 'llms', ok: true, method: 'webhook', message: 'Webhook accepted' };
  } catch (e) {
    return { target: filename === 'robots.txt' ? 'robots' : 'llms', ok: false, method: 'webhook', message: `Webhook error: ${String(e)}` };
  }
}

async function deployViaFtp(site: Site, filename: string, content: string): Promise<DeployResult | null> {
  if (!site.ftp_host || !site.ftp_user || !site.ftp_pass) return null;
  try {
    await uploadFileViaFtp(
      {
        host: site.ftp_host,
        port: site.ftp_port ?? 21,
        user: site.ftp_user,
        pass: site.ftp_pass,
        path: site.ftp_path ?? '/',
      },
      filename,
      content,
    );
    return { target: filename === 'robots.txt' ? 'robots' : 'llms', ok: true, method: 'ftp', message: 'Uploaded via FTP' };
  } catch (e) {
    return { target: filename === 'robots.txt' ? 'robots' : 'llms', ok: false, method: 'ftp', message: `FTP error: ${String(e)}` };
  }
}

async function deployFile(site: Site, filename: string, content: string): Promise<DeployResult> {
  const target: DeployTarget = filename === 'robots.txt' ? 'robots' : 'llms';
  const viaWebhook = await deployViaWebhook(site, filename, content);
  if (viaWebhook) return viaWebhook;
  const viaFtp = await deployViaFtp(site, filename, content);
  if (viaFtp) return viaFtp;
  return { target, ok: false, method: 'none', message: 'No deployment method configured (set a webhook or FTP credentials).' };
}

/**
 * Deploys robots.txt + llms.txt for a site. Returns per-file results.
 * Logs progress to the system log.
 */
export async function deployGeoFiles(site: Site): Promise<{ robots: DeployResult; llms: DeployResult; llmsSitemap: DeployResult }> {
  logSystem('info', `${site.domain} — deploying robots.txt + llms.txt + llms-sitemap.xml`, site.id);

  const robotsContent = buildRobotsTxt(site);
  // Prefer the AI-generated / hand-edited llms.txt when one has been saved.
  const llmsContent   = site.llms_txt_content?.trim() ? site.llms_txt_content : buildLlmsTxt(site);
  const sitemapContent = buildLlmsSitemap(site);

  const [robots, llms, llmsSitemap] = await Promise.all([
    deployFile(site, 'robots.txt', robotsContent),
    deployFile(site, 'llms.txt',   llmsContent),
    deployFile(site, 'llms-sitemap.xml', sitemapContent),
  ]);

  if (robots.ok) logSystem('ok', `${site.domain} — robots.txt deployed via ${robots.method}`, site.id);
  else logSystem('warn', `${site.domain} — robots.txt deploy: ${robots.message}`, site.id);

  if (llms.ok) logSystem('ok', `${site.domain} — llms.txt deployed via ${llms.method}`, site.id);
  else logSystem('warn', `${site.domain} — llms.txt deploy: ${llms.message}`, site.id);

  if (llmsSitemap.ok) logSystem('ok', `${site.domain} — llms-sitemap.xml deployed via ${llmsSitemap.method}`, site.id);
  else logSystem('warn', `${site.domain} — llms-sitemap.xml deploy: ${llmsSitemap.message}`, site.id);

  return { robots, llms, llmsSitemap };
}
