import { useCallback, useEffect, useState } from 'react';
import { Building2, Globe2, MapPin, Plus, RefreshCw, Star, Trash2, X } from 'lucide-react';
import { api, type LocalEntity, type Site } from '../api';
import { useToast } from '../AppContext';
import { useWorkspace } from '../workspace/WorkspaceContext';

const EMPTY={name:'',market:'United Kingdom',locale:'en-GB',entity_type:'brand',site_id:'',primary_url:'',address:'',phone:'',identifiers:'{}',listings:'[]',review_rating:'',review_count:''};

export default function EntitiesPage(){
  const {active}=useWorkspace();const toast=useToast();const canManage=!!active?.permissions?.manage_content;
  const[entities,setEntities]=useState<LocalEntity[]>([]);const[sites,setSites]=useState<Site[]>([]);const[composer,setComposer]=useState(false);const[editing,setEditing]=useState<LocalEntity|null>(null);const[busy,setBusy]=useState(false);const[draft,setDraft]=useState(EMPTY);
  const load=useCallback(async()=>{const[e,s]=await Promise.all([api.getLocalEntities(),api.getSites()]);setEntities(e);setSites(s)},[]);useEffect(()=>{load().catch(()=>null)},[load,active?.id]);
  function open(row?:LocalEntity){setEditing(row||null);setDraft(row?{name:row.name,market:row.market,locale:row.locale,entity_type:row.entity_type,site_id:row.site_id||'',primary_url:row.primary_url||'',address:row.address||'',phone:row.phone||'',identifiers:JSON.stringify(row.identifiers,null,2),listings:JSON.stringify(row.listings,null,2),review_rating:row.review_rating==null?'':String(row.review_rating),review_count:row.review_count==null?'':String(row.review_count)}:EMPTY);setComposer(true)}
  async function save(){let identifiers:Record<string,string>;let listings:LocalEntity['listings'];try{identifiers=JSON.parse(draft.identifiers||'{}');listings=JSON.parse(draft.listings||'[]')}catch{toast('error','Identifiers and listings must be valid JSON');return}setBusy(true);try{await api.saveLocalEntity({id:editing?.id,name:draft.name,market:draft.market,locale:draft.locale,entity_type:draft.entity_type,site_id:draft.site_id||null,primary_url:draft.primary_url||null,address:draft.address||null,phone:draft.phone||null,identifiers,listings,review_rating:draft.review_rating?Number(draft.review_rating):null,review_count:draft.review_count?Number(draft.review_count):null});setComposer(false);await load();toast('success','Market entity saved')}catch(e){toast('error',String(e).replace('Error: ',''))}setBusy(false)}
  async function remove(row:LocalEntity){if(!confirm(`Delete ${row.name} in ${row.market}?`))return;await api.deleteLocalEntity(row.id);await load()}
  return <div className="ops-page entities-page"><header className="ops-page-header"><div><span className="eyebrow"><MapPin size={13}/> Multi-market entity graph</span><h1>Markets & entities</h1><p>Keep brand facts, local identities, listings and review evidence consistent across regions and answer engines.</p></div><button className="btn btn-primary" disabled={!canManage} onClick={()=>open()}><Plus size={14}/> Add entity</button></header>
    <section className="entity-summary"><div><Globe2/><strong>{new Set(entities.map(row=>row.market)).size}</strong><span>markets</span></div><div><Building2/><strong>{entities.length}</strong><span>entities</span></div><div><Star/><strong>{entities.length?Math.round(entities.reduce((sum,row)=>sum+row.consistency_score,0)/entities.length):0}%</strong><span>knowledge consistency</span></div><p>Regional AI prompts can use the same locale and market vocabulary. Feed listing/review measures through the scoped metrics API to retain provenance over time.</p></section>
    <div className="entity-grid">{entities.map(row=><article key={row.id}><header><span className="site-monogram">{row.name.slice(0,1).toUpperCase()}</span><div><span className="eyebrow">{row.entity_type} · {row.locale}</span><h2>{row.name}</h2><p><MapPin size={10}/>{row.market}</p></div><button className="btn-icon btn-icon-ghost" disabled={!canManage} onClick={()=>remove(row)}><Trash2 size={13}/></button></header><div className="entity-score"><div style={{'--entity-score':`${row.consistency_score}%`} as React.CSSProperties}/><strong>{row.consistency_score}%</strong><span>knowledge consistency</span></div><dl><div><dt>Canonical identity</dt><dd>{row.primary_url||'Add primary URL'}</dd></div><div><dt>NAP</dt><dd>{row.address&&row.phone?'Complete':'Needs detail'}</dd></div><div><dt>Identifiers</dt><dd>{Object.keys(row.identifiers).length}</dd></div><div><dt>Listings</dt><dd>{row.listings.length}</dd></div><div><dt>Reviews</dt><dd>{row.review_rating?`${row.review_rating.toFixed(1)} · ${row.review_count||0}`:'Not connected'}</dd></div></dl><footer><span>Updated {new Date(row.updated_at).toLocaleDateString()}</span><button className="btn btn-secondary btn-sm" disabled={!canManage} onClick={()=>open(row)}>Manage facts</button></footer></article>)}{!entities.length&&<div className="ops-empty entity-empty"><MapPin/><h3>Model your first market</h3><p>Add the canonical facts customers and answer engines should agree on. This is real tenant data—no invented listing evidence.</p><button className="btn btn-secondary" disabled={!canManage} onClick={()=>open()}><Plus size={13}/> Add entity</button></div>}</div>
    {composer&&<div className="ops-modal-backdrop" onMouseDown={()=>setComposer(false)}><div className="ops-modal entity-modal" onMouseDown={event=>event.stopPropagation()}><header><div><span className="eyebrow">Canonical knowledge record</span><h2>{editing?'Update entity':'New market entity'}</h2></div><button className="btn-icon btn-icon-ghost" onClick={()=>setComposer(false)}><X/></button></header><div className="form-grid"><label>Name<input autoFocus value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Market<input value={draft.market} onChange={e=>setDraft({...draft,market:e.target.value})}/></label><label>Locale<input value={draft.locale} onChange={e=>setDraft({...draft,locale:e.target.value})}/></label><label>Type<select value={draft.entity_type} onChange={e=>setDraft({...draft,entity_type:e.target.value})}><option value="brand">Brand</option><option value="location">Location</option><option value="person">Person</option><option value="product">Product</option></select></label><label className="full">Site<select value={draft.site_id} onChange={e=>setDraft({...draft,site_id:e.target.value})}><option value="">Workspace level</option>{sites.map(site=><option key={site.id} value={site.id}>{site.name}</option>)}</select></label><label className="full">Primary URL<input type="url" value={draft.primary_url} onChange={e=>setDraft({...draft,primary_url:e.target.value})}/></label><label>Address<textarea rows={3} value={draft.address} onChange={e=>setDraft({...draft,address:e.target.value})}/></label><label>Phone<input value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label><label>Review rating<input type="number" min="0" max="5" step="0.1" value={draft.review_rating} onChange={e=>setDraft({...draft,review_rating:e.target.value})}/></label><label>Review count<input type="number" min="0" value={draft.review_count} onChange={e=>setDraft({...draft,review_count:e.target.value})}/></label><label className="full">Knowledge identifiers (JSON)<textarea className="code-input" rows={4} value={draft.identifiers} onChange={e=>setDraft({...draft,identifiers:e.target.value})} placeholder='{"sameAs":"https://www.wikidata.org/wiki/..."}'/></label><label className="full">Listings (JSON)<textarea className="code-input" rows={5} value={draft.listings} onChange={e=>setDraft({...draft,listings:e.target.value})} placeholder='[{"provider":"Google Business Profile","url":"...","status":"consistent"}]'/></label></div><footer><button className="btn btn-ghost" onClick={()=>setComposer(false)}>Cancel</button><button className="btn btn-primary" disabled={busy||!draft.name.trim()||!draft.market.trim()} onClick={save}>{busy?<RefreshCw size={13} className="spin"/>:'Save entity'}</button></footer></div></div>}
  </div>
}
