import { useCallback, useEffect, useState } from 'react';
import { ArrowRight, Check, CheckCircle2, ClipboardCheck, Code2, Eye, FileDiff, Globe2, Play, Plus, RefreshCw, Rocket, Search, ShieldCheck } from 'lucide-react';
import { api, type ContentAction, type PlatformIntegration, type Site } from '../api';
import { Modal } from '../components/Modal';
import { useToast } from '../AppContext';
import { useWorkspace } from '../workspace/WorkspaceContext';

const STEPS=['proposed','approved','staged','published','verified'] as const;
const STEP_ACTION:Record<string,{label:string;next:'approve'|'stage'|'publish'|'verify';icon:typeof Check}>={proposed:{label:'Approve',next:'approve',icon:Check},approved:{label:'Create draft',next:'stage',icon:FileDiff},staged:{label:'Publish',next:'publish',icon:Rocket},published:{label:'Verify live',next:'verify',icon:Eye}};

export default function PublishingPage(){
  const {active}=useWorkspace();const toast=useToast();const canManage=!!active?.permissions?.manage_content;
  const [actions,setActions]=useState<ContentAction[]>([]);const [integrations,setIntegrations]=useState<PlatformIntegration[]>([]);const [sites,setSites]=useState<Site[]>([]);const [composer,setComposer]=useState(false);const [busy,setBusy]=useState<string|null>(null);
  const [draft,setDraft]=useState({site_id:'',integration_id:'',kind:'metadata',title:'',rationale:'',payload:'{\n  "title": "",\n  "content": ""\n}'});
  const load=useCallback(async()=>{const[a,i,s]=await Promise.all([api.getContentActions(),api.getIntegrations(),api.getSites()]);setActions(a);setIntegrations(i.filter(row=>['wordpress','shopify','webflow'].includes(row.provider)));setSites(s)},[]);
  useEffect(()=>{load().catch(()=>null)},[load,active?.id]);
  async function advance(action:ContentAction){const step=STEP_ACTION[action.status];if(!step)return;if(step.next==='publish'&&!confirm('Publish this reviewed change to the live site? This is an explicit production action.'))return;setBusy(action.id);try{await api.advanceContentAction(action.id,step.next);await load();toast('success',`${step.label} completed`)}catch(e){toast('error',String(e).replace('Error: ',''))}setBusy(null)}
  async function rollback(action:ContentAction){if(!confirm('Restore the captured pre-change state and publish it live? This emergency action is audited.'))return;setBusy(action.id);try{await api.advanceContentAction(action.id,'rollback');await load();toast('success','Prior live state restored')}catch(e){toast('error',String(e).replace('Error: ',''))}setBusy(null)}
  async function audit(siteId?:string){setBusy('audit');try{const result=await api.auditContent(siteId);toast('success',`Audited ${result.pages} pages and created ${result.issues} evidence-backed actions`)}catch(e){toast('error',String(e).replace('Error: ',''))}setBusy(null)}
  async function create(){let payload:Record<string,unknown>;try{payload=JSON.parse(draft.payload)}catch{toast('error','Payload must be valid JSON');return}setBusy('create');try{await api.createContentAction({...draft,site_id:draft.site_id||undefined,integration_id:draft.integration_id||undefined,payload});setComposer(false);await load();toast('success','Change proposed for review')}catch(e){toast('error',String(e).replace('Error: ',''))}setBusy(null)}
  return <div className="ops-page publishing-page"><header className="ops-page-header"><div><span className="eyebrow"><ShieldCheck size={13}/> Governed delivery</span><h1>Content & publishing</h1><p>Propose with evidence, approve deliberately, stage a draft, publish explicitly and verify the live result.</p></div><div className="header-actions"><button className="btn btn-secondary" disabled={busy==='audit'||!canManage} onClick={()=>audit()}>{busy==='audit'?<RefreshCw className="spin" size={14}/>:<Search size={14}/>} Audit content</button><button className="btn btn-primary" disabled={!canManage} onClick={()=>setComposer(true)}><Plus size={14}/> Propose change</button></div></header>
    <section className="publishing-principle"><FileDiff/><div><strong>No silent AI publishing.</strong><span>Every remote mutation moves through a visible approval state. Drafting and publishing are separate API calls; live verification is retained on the causal timeline.</span></div><span className="principle-flow">Evidence <ArrowRight/> Review <ArrowRight/> Draft <ArrowRight/> Publish <ArrowRight/> Verify</span></section>
    <div className="publishing-board">{actions.map(action=>{const current=Math.max(0,STEPS.indexOf(action.status as typeof STEPS[number]));const control=STEP_ACTION[action.status];const Icon=control?.icon;const canRollback=['published','verified','failed'].includes(action.status)&&Object.keys(action.rollback_payload||{}).length>0;return <article key={action.id} className={`publish-card status-${action.status}`}><header><div><span className="source-badge">{action.kind.replaceAll('_',' ')}</span>{action.site_id&&<span className="site-badge"><Globe2 size={11}/>{sites.find(s=>s.id===action.site_id)?.name||'Site'}</span>}</div><span className={`connection-status ${action.status==='failed'?'error':'connected'}`}><i/>{action.status.replaceAll('_',' ')}</span></header><h2>{action.title}</h2><p>{action.rationale||'No rationale supplied.'}</p><div className="approval-rail">{STEPS.map((step,index)=><div key={step} className={index<current?'done':index===current?'current':''}><i>{index<current?<Check size={10}/>:index+1}</i><span>{step}</span></div>)}</div><details><summary><Code2 size={13}/> Proposed payload</summary><pre>{JSON.stringify(action.payload,null,2)}</pre></details>{action.last_error&&<div className="publish-error">{action.last_error}</div>}<footer><span>{new Date(action.created_at).toLocaleDateString()}{action.preview_url&&<> · <a href={action.preview_url} target="_blank" rel="noreferrer">Preview</a></>}</span>{control&&<button className={`btn ${control.next==='publish'?'btn-danger':'btn-primary'} btn-sm`} disabled={!canManage||busy===action.id} onClick={()=>advance(action)}>{busy===action.id?<RefreshCw className="spin" size={12}/>:Icon&&<Icon size={12}/>} {control.label}</button>}{canRollback&&<button className="btn btn-ghost btn-sm" disabled={!canManage||busy===action.id} onClick={()=>rollback(action)}>Rollback</button>}{action.status==='verified'&&<span className="verified-chip"><CheckCircle2 size={13}/> Verified live</span>}</footer></article>})}{!actions.length&&<div className="ops-empty publish-empty"><ClipboardCheck/><h3>Your approval queue is clear</h3><p>Run the content inventory to surface evidence-backed fixes, or propose a change manually.</p><button className="btn btn-secondary" disabled={!canManage} onClick={()=>setComposer(true)}><Plus size={13}/> Propose the first change</button></div>}</div>
    {composer&&<Modal onClose={()=>setComposer(false)} size="lg" className="publish-modal" title="Propose a content change" eyebrow="Evidence-backed proposal" description="Define the change and its evidence. Nothing is published until the approval workflow is complete." icon={<FileDiff/>} footer={<><button className="btn btn-ghost" onClick={()=>setComposer(false)}>Cancel</button><button className="btn btn-primary" disabled={busy==='create'||!draft.title.trim()} onClick={create}>{busy==='create'?'Creating…':<><Play size={13}/> Add to approval queue</>}</button></>}><div className="form-grid"><label>Site<select value={draft.site_id} onChange={e=>setDraft({...draft,site_id:e.target.value})}><option value="">Workspace level</option>{sites.map(site=><option key={site.id} value={site.id}>{site.name}</option>)}</select></label><label>Publishing connection<select value={draft.integration_id} onChange={e=>setDraft({...draft,integration_id:e.target.value})}><option value="">Choose later</option>{integrations.map(row=><option key={row.id} value={row.id}>{row.name} · {row.provider}</option>)}</select></label><label>Change type<select value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value})}><option value="metadata">Metadata</option><option value="content_update">Content update</option><option value="schema">Structured data</option><option value="internal_links">Internal links</option><option value="llms_txt">llms.txt</option></select></label><label className="full">Title<input data-autofocus value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Describe the proposed change"/></label><label className="full">Rationale<textarea rows={3} value={draft.rationale} onChange={e=>setDraft({...draft,rationale:e.target.value})} placeholder="What evidence supports this change and what should improve?"/></label><label className="full">Adapter payload (JSON)<textarea className="code-input" rows={10} value={draft.payload} onChange={e=>setDraft({...draft,payload:e.target.value})}/><small>WordPress accepts title/content/excerpt/post_type/remote_id. Webflow accepts collection_id and fieldData. Shopify accepts remote_id and article.</small></label></div></Modal>}
  </div>
}
