import { useCallback, useEffect, useState } from 'react';
import { CalendarDays, CheckCircle2, Download, Eye, FileBarChart, Mail, Palette, Plus, RefreshCw, Send, Sparkles, X } from 'lucide-react';
import { api, getActiveWorkspaceId, type ReportRun, type ReportTemplate } from '../api';
import { useToast } from '../AppContext';
import { useWorkspace } from '../workspace/WorkspaceContext';

export default function ReportsPage(){
  const {active}=useWorkspace();const toast=useToast();const canManage=!!active?.permissions?.manage_reports;
  const [templates,setTemplates]=useState<ReportTemplate[]>([]);const[runs,setRuns]=useState<ReportRun[]>([]);const[governance,setGovernance]=useState<Record<string,string>>({});const[composer,setComposer]=useState(false);const[busy,setBusy]=useState<string|null>(null);
  const[digestRecipients,setDigestRecipients]=useState('');
  const[draft,setDraft]=useState({name:'Monthly organic intelligence',cadence:'monthly',recipients:'',title:'',accent:'#7c5cff',footer:''});
  const load=useCallback(async()=>{const[t,r,g]=await Promise.all([api.getReportTemplates(),api.getReportRuns(),api.getGovernance()]);setTemplates(t);setRuns(r);setGovernance(g);try{const parsed=JSON.parse(g.digest_recipients||'[]');setDigestRecipients(Array.isArray(parsed)?parsed.join(', '):'')}catch{setDigestRecipients(g.digest_recipients||'')}},[]);useEffect(()=>{load().catch(()=>null)},[load,active?.id]);
  async function create(){setBusy('create');try{await api.createReportTemplate({name:draft.name,cadence:draft.cadence,recipients:draft.recipients.split(/[\s,]+/).filter(Boolean),branding:{title:draft.title||undefined,accent:draft.accent,footer:draft.footer||undefined}});setComposer(false);await load();toast('success','Report template created')}catch(e){toast('error',String(e).replace('Error: ',''))}setBusy(null)}
  async function generate(template:ReportTemplate,email=false){setBusy(template.id);try{const result=await api.generateReport({template_id:template.id,email});await load();toast('success',email?`Report generated and sent to ${result.emailed} recipients`:'Report snapshot generated')}catch(e){toast('error',String(e).replace('Error: ',''))}setBusy(null)}
  async function preview(id:string){try{const headers=new Headers();const ws=getActiveWorkspaceId();if(ws)headers.set('X-Workspace-Id',ws);const res=await fetch(`/api/platform/reports/${id}?format=html`,{headers,credentials:'same-origin'});if(!res.ok)throw new Error('Preview could not be loaded');const blob=await res.blob();window.open(URL.createObjectURL(blob),'_blank','noopener,noreferrer')}catch(e){toast('error',String(e).replace('Error: ',''))}}
  async function saveDigest(){setBusy('digest');try{const recipients=digestRecipients.split(/[\s,]+/).filter(Boolean);await api.saveGovernance({digest_cadence:governance.digest_cadence||'weekly',digest_recipients:recipients});setGovernance({...governance,digest_recipients:JSON.stringify(recipients)});toast('success','Digest routing saved')}catch(e){toast('error',String(e).replace('Error: ',''))}setBusy(null)}
  return <div className="ops-page reports-page"><header className="ops-page-header"><div><span className="eyebrow"><FileBarChart size={13}/> Proof, packaged</span><h1>Reports & digests</h1><p>Client-ready snapshots from the same governed evidence that powers the dashboard—never a second set of numbers.</p></div><button className="btn btn-primary" disabled={!canManage} onClick={()=>setComposer(true)}><Plus size={14}/> New template</button></header>
    <section className="report-feature"><div><span className="eyebrow"><Sparkles size={13}/> Branded storytelling</span><h2>From visibility to business outcome, in one narrative.</h2><p>Combine executive health, search momentum, AI share of voice, page experience, completed work and provider billback. Every snapshot preserves the reporting period and source evidence.</p><div className="report-feature-points"><span><CheckCircle2/> Workspace branding</span><span><CalendarDays/> Scheduled delivery</span><span><Palette/> Responsive email-safe HTML</span></div></div><div className="report-mock"><header><i/><span>Organic intelligence · August</span></header><strong>82</strong><small>portfolio health</small><div><i style={{width:'78%'}}/><i style={{width:'61%'}}/><i style={{width:'88%'}}/></div><footer>Search · AI · Experience · Operations</footer></div></section>
    <div className="ops-split reports-split"><section className="ops-card"><div className="ops-card-head"><div><span className="eyebrow">Reusable narratives</span><h2>Templates</h2></div><span>{templates.length} templates</span></div><div className="template-list">{templates.map(template=><article key={template.id}><span className="template-icon"><FileBarChart/></span><div><strong>{template.name}</strong><small>{template.cadence==='manual'?'On demand':`${template.cadence} · next ${template.next_run_at?new Date(template.next_run_at).toLocaleDateString():'after first run'}`}</small><p>{template.recipients.length?`${template.recipients.length} recipient${template.recipients.length===1?'':'s'}`:'No email recipients'}</p></div><button className="btn btn-secondary btn-sm" disabled={!canManage||busy===template.id} onClick={()=>generate(template,false)}>{busy===template.id?<RefreshCw className="spin" size={12}/>:<FileBarChart size={12}/>} Generate</button>{template.recipients.length>0&&<button className="btn btn-primary btn-sm" disabled={!canManage||busy===template.id} onClick={()=>generate(template,true)}><Send size={12}/> Send</button>}</article>)}{!templates.length&&<div className="ops-empty compact"><FileBarChart/><strong>No templates yet</strong><span>Create a branded report once, then schedule or run it on demand.</span></div>}</div></section>
      <aside className="ops-card digest-card"><div className="ops-card-head"><div><span className="eyebrow">Operating rhythm</span><h2>Workspace digest</h2></div><Mail/></div><p>Send a concise list of priority work, organic momentum and AI visibility to the people responsible for acting.</p><label>Cadence<select value={governance.digest_cadence||'off'} onChange={e=>setGovernance({...governance,digest_cadence:e.target.value})}><option value="off">Off</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select></label><label>Recipients<textarea rows={3} value={digestRecipients} onChange={e=>setDigestRecipients(e.target.value)} placeholder="client@example.com, team@example.com"/><small>Separate email addresses with a comma or new line.</small></label><div><button className="btn btn-secondary btn-sm" disabled={!canManage||busy==='digest'} onClick={saveDigest}>Save routing</button><button className="btn btn-ghost btn-sm" disabled={!canManage} onClick={()=>api.sendDigest().then(r=>toast(r.sent?'success':'info',r.sent?'Digest sent':'Add recipients and SMTP first')).catch(e=>toast('error',String(e)))}><Send size={12}/> Send now</button></div></aside>
    </div>
    <section className="ops-card"><div className="ops-card-head"><div><span className="eyebrow">Immutable snapshots</span><h2>Report history</h2></div><span>{runs.length} generated</span></div><div className="report-run-list">{runs.map(run=><div key={run.id}><span className={`run-dot ${run.status==='complete'?'completed':run.status}`}/><div><strong>{templates.find(t=>t.id===run.template_id)?.name||'Ad-hoc intelligence report'}</strong><small>{new Date(run.period_start).toLocaleDateString()} → {new Date(run.period_end).toLocaleDateString()} · generated {new Date(run.created_at).toLocaleString()}</small></div><span className={`connection-status ${run.status==='complete'?'connected':'error'}`}><i/>{run.status}</span>{run.status==='complete'&&<button className="btn btn-secondary btn-sm" onClick={()=>preview(run.id)}><Eye size={12}/> Preview</button>}</div>)}{!runs.length&&<div className="ops-empty compact">Generated snapshots appear here with their exact reporting period.</div>}</div></section>
    {composer&&<div className="ops-modal-backdrop" onMouseDown={()=>setComposer(false)}><div className="ops-modal" onMouseDown={e=>e.stopPropagation()}><header><div><span className="eyebrow">Reusable client story</span><h2>New report template</h2></div><button className="btn-icon btn-icon-ghost" onClick={()=>setComposer(false)}><X/></button></header><div className="form-grid"><label className="full">Template name<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Cadence<select value={draft.cadence} onChange={e=>setDraft({...draft,cadence:e.target.value})}><option value="manual">On demand</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label>Accent colour<input type="color" value={draft.accent} onChange={e=>setDraft({...draft,accent:e.target.value})}/></label><label className="full">Client-facing title<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Defaults to workspace name"/></label><label className="full">Recipients<input value={draft.recipients} onChange={e=>setDraft({...draft,recipients:e.target.value})} placeholder="client@example.com, team@example.com"/></label><label className="full">Footer<textarea value={draft.footer} onChange={e=>setDraft({...draft,footer:e.target.value})} rows={2}/></label></div><footer><button className="btn btn-ghost" onClick={()=>setComposer(false)}>Cancel</button><button className="btn btn-primary" disabled={!draft.name.trim()||busy==='create'} onClick={create}><Download size={13}/> Create template</button></footer></div></div>}
  </div>
}
